spring:
  flyway:
    enabled: 'false'
    validateOnMigrate: 'true'
    password: ${spring.datasource.password}
    user: ${spring.datasource.username}
    sqlMigrationSeparator: __
    locations: classpath:db/migration
    url: ${spring.datasource.url}
    table: FLYWAY_SCHEMA_HISTORY
    sqlMigrationPrefix: US_
  datasource:
    driverClassName: org.postgresql.Driver
    password: postgres
    username: postgres
    url: jdbc:postgresql://postgres:5432/gokart
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: gokart-service
  security:
    user:
      name: user
      password: userpassword
server:
  error:
    include-stacktrace: never
    include-message: always
  port: '8080'